// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: maven-multimodules
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-10-04
:page-description: Learn how to build an application consisting of JAR, WAR, and EAR modules with Maven
:page-related-guides: ['maven-intro']
:page-tags: []
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Creating a multi-module application

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

You will learn how to build an application with multiple modules with Maven and Open Liberty.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

A Java Platform, Enterprise Edition (Java EE) application consists of modules that work together as one entity. An enterprise archive (EAR) is a wrapper for a Java EE application, which consists of web archive (WAR) and Java archive (JAR) files. Package modules and resources into an EAR file to deploy or distribute the Java EE application to new environments.

You will learn how to establish a dependency between a web module and a Java library module. Next, use Maven to package the WAR file and the JAR file into an EAR file so that you can run and test the application on Open Liberty.

You will build a unit converter application that converts heights from centimeters into feet and inches. Enter heights in centimeters from a web page, and the application processes the input with functions in the JAR file to return the corresponding height in Imperial units.

When the application is running, you can access the unit converter at the following location:

[source, role="no_copy"]
----
http://localhost:9080/converter/
----


// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

Access partial implementation of the application from the `start` folder. This folder includes a web module in the `war` folder, a Java library in the `jar` folder, and template files in the `ear` folder. However, the Java library and the web module are independent projects, and you will need to complete the following steps to implement the application:

1. Add a dependency relationship between two modules.

2. Assemble the entire application into an EAR file.

3. Test the multi-module application.

4. Aggregate the entire build.


// =================================================================================================
// Adding dependencies between WAR and JAR modules
// =================================================================================================

== Adding dependencies between WAR and JAR modules

To use the Java library in your web module, add a dependency relationship between them.

As you might notice, each module has its own `pom.xml` file because each module is treated as an independent project. You can rebuild, reuse, and reassemble every module on its own.

Navigate to the `start` directory to begin.

[role="code_command hotspot=36-40", subs="quotes"]
----
Edit the POM file.
`war/pom.xml`
----
pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/war/pom.xml[tags=**]
----
Go to the dependency section, where you can add more dependencies. Add the [hotspot=36-40 file=0]`<dependency/>` element: the Java library module that implements the functions that you need for the unit converter.

After you add the dependency, use any functions included in the library in the [hotspot=1-51 file=1]`HeightsBean.java` class of the web module.

[role="code_command hotspot=3-51", subs="quotes"]
----
Edit the `HeightsBean` class.
`war/src/main/java/io/openliberty/guides/multimodules/web/HeightsBean.java`
----
HeightsBean.java
[source, Java, linenums, role='code_column']
----
include::finish/war/src/main/java/io/openliberty/guides/multimodules/web/HeightsBean.java[tags=**;!copyright]
----

Add the [hotspot=35 file=1]`getFeet(cm)` to the [hotspot=33-38 file=1]`setHeightFeet` method to convert a measurement into feet.

Then, add [hotspot=42 file=1]`getInches(cm)` to the [hotspot=40-45 file=1]`setHeightInches` method to convert a measurement into inches.


// =================================================================================================
// Assembling multiple modules into an EAR file
// =================================================================================================

== Assembling multiple modules into an EAR file

To deploy the entire application on the Open Liberty server, first package the application. Use the EAR project to assemble multiple modules into an EAR file.

Navigate to the `ear` folder and find a template `pom.xml` file. 
[role="code_command hotspot=7-63", subs="quotes"]
----
Edit the POM file.
`ear/pom.xml`
----
pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/ear/pom.xml[tags=**]
----

Set the [hotspot=7-11 file=0]`basic configuration` for the project and set the [hotspot=11 file=0]`<packaging/>` element to `ear`.

Next, add the dependencies. Define the [hotspot=21-26 file=0]`Java library module` and the [hotspot=27-32 file=0]`web module` as dependencies. Specify [hotspot=31 file=0]`<type>war</type>` for the web module. If you don’t specify the web module, Maven looks for a JAR file.

Add the definition and configuration of the [hotspot=43-63 file=0]`maven-ear-plugin` plug-in for creating an EAR file. Define the [hotspot=49-53 file=0]`<jarModule>` and [hotspot=54-60 file=0]`<webModule>` modules to be packaged into the EAR file.
To customize the context root of the application, set the appropriate contextRoot in the webModule. Otherwise, Maven automatically uses the WAR file `artifactId` ID as the context root for the application while generating the `application.xml` file.

To download and start an Open Liberty server, use the [hotspot=66-96 file=0]`liberty-maven-plugin` plug-in for Maven. This configuration is provided, and the executions of the plug-in follow the typical phases of a Maven life cycle.

To deploy the EAR application, you need to congiure a server.

[role="code_command hotspot=1-18", subs="quotes"]
----
Create the server configuration file.
`ear/src/main/liberty/config`
----
server.xml
[source, xml, linenums, role='code_column']
----
include::finish/ear/src/main/liberty/config/server.xml[tags=**]
----

// =================================================================================================
// Building the modules
// =================================================================================================

== Building the modules

To build the three modules, run the following commands from the `jar` directory, `war` directory, and `ear` directory in that order. Start with the `jar` directory, proceed to the `war` directory, and end with the `ear` directory.

[role=command]
----
mvn clean install
----

These commands create a JAR file in the `jar/target` directory, a WAR file in the `war/target` directory, and an EAR file in the `ear/target` directory, which contains the JAR and WAR files.


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To deploy your EAR application on an Open Liberty server, run the Maven `liberty:start-server` goal from the `ear` directory:

[role=command]
----
cd ../../start/ear
mvn liberty:start-server
----

Once the server is running, you can find the application at the following URL: http://localhost:9080/converter/

To stop the server, enter the following command:

[role=command]
----
mvn liberty:stop-server
----


// =================================================================================================
// Testing the multi-module application
// =================================================================================================

== Testing the multi-module application

To test the multi-module application, add integration tests to the EAR project.

Navigate to the `start/ear/src/test/java/it/io/openliberty/guides/multimodules` directory. Open the [hotspot=1-52 file=0]`Test.java` file. Helper functions for the integration test class are provided.

[role="code_command hotspot=11-52", subs="quotes"]
----
Edit the `Test` class.
`start/ear/src/test/java/it/io/openliberty/guides/multimodules`
----
Test.java
[source, Java, linenums, role='code_column']
----
include::finish/ear/src/test/java/it/io/openliberty/guides/multimodules/Test.java[tags=**;!copyright]
----

Add the [hotspot=17-23 file=0]`testIndexPage` test to check that you can access the landing page.

Add the [hotspot=26-31 file=0]`testHeightsPage` test to check that the application can process the input value and calculate the result correctly.

For a Maven EAR project, the [hotspot=107 file=1]`testCompile` goal is specified for the [hotspot=99-111 file=1]`maven-compiler-plugin` plug-in in your `ear/pom.xml` file so that the test cases are compiled and picked up for execution.

pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/ear/pom.xml[tags=**]
----

Enter the following command to run the test from the `start/ear` directory:

[role=command]
----
mvn verify
----

If the tests pass, you will see a similar output to the following:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.multimodules.Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.712 sec - in it.io.openliberty.guides.multimodules.Test

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

----


// =================================================================================================
// Aggregating the entire build
// =================================================================================================

== Aggregating the entire build

Because you have multiple modules, aggregate the Maven projects to simplify the build process.

Create a parent `pom.xml` file under the `start` directory to link all of the child modules together. A template is provided for you.

[role="code_command hotspot=13-23", subs="quotes"]
----
Edit the POM file.
`start/pom.xml`
----
pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/pom.xml[tags=**]
----
Set the [hotspot=13-17 file=0]`basic configuration` for the project. Set `pom` as the [hotspot=17 file=0]`<packaging/>` element of the parent `pom.xml` file. Specify `io.openliberty.guides` as the [hotspot=14 file=0]`<groupId/>` ID, which the child `pom.xml` files will inherit.

In the parent `pom.xml` file, list all of the [hotspot=19-23 file=0]`<modules/>` that you want to aggregate for the application.

Lastly,
[role="code_command hotspot=1-5", subs="quotes"]
----
Add a `&ltparent/&gt;` section to each of the `pom.xml` files in the child modules,
such as the `jar`, `war`, and `ear` projects.
----
pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/ear/pom.xml[tags=parent]
----


// =================================================================================================
// Building the application
// =================================================================================================

== Building the application

Use the following command to build the entire application from the `start` directory:

[role=command]
----
mvn clean install
----

You no longer need to execute multiple `mvn install` commands from different directories. With a single command, you can build and test the whole application and all of the modules.


// =================================================================================================
// Congratulations! You're done!
// =================================================================================================

== Great work! You're done!

You built and tested a multi-module unit converter application on the with Maven in Open Liberty.


include::{common-includes}/finish.adoc[]
include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]
